import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {archive,splitArchive,restore,cleanName} from '../zip-core.mjs';
const dir=join(tmpdir(),'cnation-zip-legacy-test');await mkdir(dir,{recursive:true});
const text=new File(['한글 문서입니다.\n'.repeat(10000)],'보고서.txt');
const nested=await archive([text,new File([''],'빈 파일.txt')],()=>{},['자료/보고서.txt','자료/빈 파일.txt']);
assert.ok(nested.blob.size<text.size/5,'real deflate compression');
await writeFile(dir+'/korean.zip',new Uint8Array(await nested.blob.arrayBuffer()));
const original=randomBytes(11000000);
const a=await archive([new File([original],'원본.zip')]);
const sizeParts=await splitArchive(a.blob,'첨부파일','size',10);
assert.equal(sizeParts.length,2);assert.equal(sizeParts[0].name,'첨부파일_01.zip');
assert.ok(sizeParts.every(p=>p.blob.size<=10000000),'hard size upper bound');
const restored=await restore(sizeParts.toReversed().map(p=>p.blob));
assert.deepEqual(await restored[0].blob.arrayBuffer(),await a.blob.arrayBuffer());
await writeFile(dir+'/restored.zip',new Uint8Array(await restored[0].blob.arrayBuffer()));
await writeFile(dir+'/original.bin',original);
await writeFile(dir+'/part_01.zip',new Uint8Array(await sizeParts[0].blob.arrayBuffer()));
const countParts=await splitArchive(a.blob,'테스트.zip','count',3);assert.equal(countParts.length,3);
assert.equal(countParts[0].name,'테스트_01.zip');
assert.deepEqual(await (await restore(countParts.map(p=>p.blob)))[0].blob.arrayBuffer(),await a.blob.arrayBuffer());
await assert.rejects(()=>restore(countParts.slice(0,2).map(p=>p.blob)),/3개/);
await assert.rejects(()=>restore([countParts[0].blob,countParts[0].blob,countParts[2].blob]),/중복/);
await assert.rejects(()=>restore([countParts[0].blob,countParts[1].blob,sizeParts[1].blob]),/섞여/);
const bad=new Uint8Array(await countParts[0].blob.arrayBuffer());bad[1000]^=1;
await assert.rejects(()=>restore([new Blob([bad]),...countParts.slice(1).map(p=>p.blob)]),/손상/);
await assert.rejects(()=>splitArchive(a.blob,'test','count',2.5));
await assert.rejects(()=>splitArchive(a.blob,'test','count',201));
const one=await splitArchive(nested.blob,'작은 파일','size',10);assert.equal(one.length,1);assert.equal(one[0].blob,nested.blob);assert.equal(one[0].ordinary,true);
const oldCS=globalThis.CompressionStream;globalThis.CompressionStream=undefined;
const fallback=await archive([text]);assert.equal(fallback.canCompress,false);globalThis.CompressionStream=oldCS;
await writeFile(dir+'/fallback.zip',new Uint8Array(await fallback.blob.arrayBuffer()));
assert.equal(cleanName('../x/y.zip'),'_x_y');
console.log('PASS: compression, nested Korean paths, empty files, existing ZIP input, 10 MB cap, exact count, reordered restoration, missing/duplicate/mixed/corrupt rejection, single part, STORE fallback.');
